Repository codestates-seb/seb41_main_017, pull requests merged in 2023-01, with the labels that each got.

#7 [BE] 도메인 설계 및 JPA 연관관계 설정
  .gitignore
  server/culinari/.gitignore
  server/culinari/build.gradle
  server/culinari/src/main/java/com/codestates/culinari/audit/AuditingFields.java
  server/culinari/src/main/java/com/codestates/culinari/config/JpaConfig.java
  server/culinari/src/main/java/com/codestates/culinari/config/SecurityConfiguration.java
  server/culinari/src/main/java/com/codestates/culinari/customerservice/entity/CsInquiry.java
  server/culinari/src/main/java/com/codestates/culinari/customerservice/entity/CsNotice.java
  server/culinari/src/main/java/com/codestates/culinari/global/advice/ErrorResponse.java
  server/culinari/src/main/java/com/codestates/culinari/global/advice/GlobalExceptionAdvice.java
  server/culinari/src/main/java/com/codestates/culinari/global/exception/BusinessLogicException.java
  server/culinari/src/main/java/com/codestates/culinari/global/exception/ExceptionCode.java
  server/culinari/src/main/java/com/codestates/culinari/order/entitiy/Cart.java
  server/culinari/src/main/java/com/codestates/culinari/order/entitiy/OrderDetail.java
  server/culinari/src/main/java/com/codestates/culinari/order/entitiy/Orders.java
  server/culinari/src/main/java/com/codestates/culinari/order/entitiy/StatusType.java
  server/culinari/src/main/java/com/codestates/culinari/pagination/PageInfo.java
  server/culinari/src/main/java/com/codestates/culinari/pagination/PageResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/pagination/service/Impl/PaginationServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/Category.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/CategoryDetail.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/Product.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductInquiry.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReview.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReviewLike.java
  server/culinari/src/main/java/com/codestates/culinari/response/SingleResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/GenderType.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/Profile.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/RoleType.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/UserRole.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/Users.java
  server/culinari/src/main/resources/application.properties
  server/culinari/src/main/resources/application.yaml
  server/culinari/src/main/resources/banner.txt
  server/culinari/src/main/resources/data.sql
Labels: :art: Style, ✨ Feat

#14 #9 - 회원가입 & 로그인 구현
  server/culinari/.gitignore
  server/culinari/build.gradle
  server/culinari/src/main/java/com/codestates/culinari/config/JpaConfig.java
  server/culinari/src/main/java/com/codestates/culinari/config/SecurityConfig.java
  server/culinari/src/main/java/com/codestates/culinari/config/SecurityConfiguration.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/dto/CustomPrincipal.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/dto/CustomUserDetails.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/filter/JwtAuthenticationFilter.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/filter/JwtVerificationFilter.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/handler/MemberAccessDeniedHandler.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/handler/MemberAuthenticationEntryPoint.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/handler/MemberAuthenticationFailureHandler.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/handler/MemberAuthenticationSuccessHandler.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/jwt/JwtTokenizer.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/service/CustomUserDetailsService.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/utils/ErrorResponder.java
  server/culinari/src/main/java/com/codestates/culinari/global/exception/ExceptionCode.java
  server/culinari/src/main/java/com/codestates/culinari/user/constant/GenderType.java
  server/culinari/src/main/java/com/codestates/culinari/user/constant/RoleType.java
  server/culinari/src/main/java/com/codestates/culinari/user/controller/UserController.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/ProfileDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/UserDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/request/SignInDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/request/SignUpDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/response/ProfileMyPageResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/GenderType.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/Profile.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/UserRole.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/Users.java
  server/culinari/src/main/java/com/codestates/culinari/user/repository/ProfileRepository.java
  server/culinari/src/main/java/com/codestates/culinari/user/repository/UserRepository.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/Impl/ProfileServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/Impl/UserServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/ProfileService.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/UserService.java
Labels: 🚀 Chore, 💡 Comment, ✨ Feat, ⚒ Refactor

#16 [BE] 상품 조회 및, 상품 후기 문의 CRUD
  .github/ISSUE_TEMPLATE/이슈-양식.md
  .github/pull_request_template.md
  server/culinari/.gitignore
  server/culinari/build.gradle
  server/culinari/src/main/java/com/codestates/culinari/config/JpaConfig.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/dto/CustomPrincipal.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/dto/CustomUserDetails.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/jwt/JwtTokenizer.java
  server/culinari/src/main/java/com/codestates/culinari/customerservice/repository/CsInquiryRepository.java
  server/culinari/src/main/java/com/codestates/culinari/customerservice/repository/CsNoticeRepository.java
  server/culinari/src/main/java/com/codestates/culinari/global/advice/GlobalExceptionAdvice.java
  server/culinari/src/main/java/com/codestates/culinari/pagination/PageInfo.java
  server/culinari/src/main/java/com/codestates/culinari/pagination/PageResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/pagination/service/impl/PaginationServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/CategoryController.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductCollectionsController.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductController.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/CategoryDetailDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/CategoryDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductInquiryDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/request/ProductInquiryRequest.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/request/ProductReviewRequest.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/CategoryDetailResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/CategoryResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductInquiryResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductResponseToPageDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductResponseWithCSDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductReviewResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/Category.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/CategoryDetail.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/Product.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductInquiry.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReview.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/CategoryDetailRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/CategoryRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductInquiryRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductReviewRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/CategoryDetailService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/CategoryService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductCsService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/CategoryDetailServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/CategoryServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductCsServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/ProfileDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/Profile.java
  server/culinari/src/main/resources/data.sql
Labels: :art: Style, ✨ Feat, ⚒ Refactor

#18 #16 코드 변경 사항 수정
  server/culinari/build.gradle
  server/culinari/src/main/java/com/codestates/culinari/product/controller/CategoryController.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductCollectionsController.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductController.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/CategoryDetailDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/CategoryDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductInquiryDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/request/ProductInquiryRequest.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/request/ProductReviewRequest.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/CategoryDetailResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/CategoryResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductInquiryResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductResponseToPage.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductResponseWithCustomerService.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductReviewResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReview.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReviewLike.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/CategoryDetailRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/CategoryRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductInquiryRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductReviewRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/CategoryDetailService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductCsService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/CategoryDetailServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/CategoryServiceImpl.java
Labels: :art: Style, ⚒ Refactor

#23 [BE] 장바구니 CRUD 구현
  server/culinari/src/main/java/com/codestates/culinari/config/JpaConfig.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/dto/CustomPrincipal.java
  server/culinari/src/main/java/com/codestates/culinari/global/exception/ExceptionCode.java
  server/culinari/src/main/java/com/codestates/culinari/order/controller/CartController.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/CartDto.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/request/CartPatch.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/request/CartPost.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/response/CartResponse.java
  server/culinari/src/main/java/com/codestates/culinari/order/entitiy/Cart.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/CartRepository.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/CartService.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/impl/CartServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductCollectionsController.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/ProfileDto.java
Labels: ✨ Feat

#25 [BE] 주문 기능 구현
  server/culinari/src/main/java/com/codestates/culinari/global/exception/ExceptionCode.java
  server/culinari/src/main/java/com/codestates/culinari/order/constant/StatusType.java
  server/culinari/src/main/java/com/codestates/culinari/order/controller/OrdersController.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/OrderDetailDto.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/OrderDto.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/request/OrderRequest.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/response/OrderDetailResponse.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/response/OrderResponse.java
  server/culinari/src/main/java/com/codestates/culinari/order/entitiy/OrderDetail.java
  server/culinari/src/main/java/com/codestates/culinari/order/entitiy/Orders.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/OrderDetailRepository.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/OrdersRepository.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrdersRepositoryCustom.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrdersRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/CartService.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/OrdersService.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/impl/OrdersServiceImpl.java
Labels: ✨ Feat, ⚒ Refactor

#29 [FE] 메인페이지 구성 컴포넌트 구현, 메인페이지 구현
  client/package-lock.json
  client/package.json
  client/src/assets/gray_arrow.svg
  client/src/assets/white_arrow.svg
  client/src/components/MainBanner.jsx
  client/src/components/ProductItem.jsx
  client/src/components/ProductItemSlider.jsx
  client/src/pages/index.js
  client/src/pages/index.jsx
Labels: ✨ Feat

#32 [BE] 마이페이지 상품 문의 및 후기 리스트 출력 구현
  server/culinari/src/main/java/com/codestates/culinari/product/controller/MypageController.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductController.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductInquiryDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewLikeDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/request/ProductInquiryRequest.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/request/ProductReviewLikeRequest.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/request/ProductReviewRequest.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/CategoryDetailResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/CategoryResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductInquiryResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductInquiryResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductResponseToPageDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductResponseWithCSDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductReviewResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductReviewResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductInquiry.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReview.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReviewLike.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductInquiryRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductReviewLikeRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductCsService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductCsServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/ProfileDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/response/ProfileMyPageInquiryResponse.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/response/ProfileMyPageReviewResponse.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/Profile.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/Impl/ProfileServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/ProfileService.java
Labels: ✨ Feat, ⚒ Refactor

#34 [BE] 리뷰 좋아요 구현
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewLikeDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductReviewResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReview.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReviewLike.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductReviewLikeRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductCsServiceImpl.java
  server/culinari/src/main/resources/application.yaml
Labels: ✨ Feat

#43 [FE] 장바구니 페이지 구성 컴포넌트, 페이지 레이아웃 구현
  client/src/App.css
  client/src/App.js
  client/src/assets/cart_icon.svg
  client/src/assets/check-box-icon.svg
  client/src/assets/delete-icon.svg
  client/src/assets/minus-icon.svg
  client/src/assets/plus-icon.svg
  client/src/components/BasicButton.jsx
  client/src/components/CheckBox.jsx
  client/src/components/ColorButton.jsx
  client/src/components/DeleteButton.jsx
  client/src/components/QuantityBox.jsx
  client/src/components/Tap.jsx
  client/src/components/cart/CartProductItem.jsx
  client/src/pages/cart/index.js
  client/src/pages/index.jsx
  client/src/pages/mypage/deliverySet.js
  client/src/pages/mypage/index.js
  client/src/pages/mypage/userinfo.js
Labels: ✨ Feat

#44 [FE] ProductItem 컴포넌트 css 수정
  client/src/components/ProductItem.jsx
Labels: 💄 CSS

#45 [BE] 고객센터 구현
  server/culinari/src/main/java/com/codestates/culinari/customercenter/constant/ProcessStatus.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/controller/CustomerInquiryController.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/controller/CustomerNoticeController.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/CsInquiryDto.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/CsNoticeDto.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/request/CsInquiryRequest.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/request/CsNoticePost.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/response/CsInquiryResponse.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/response/CsNoticeResponse.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/entity/CsInquiry.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/entity/CsNotice.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/repository/CsInquiryRepository.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/repository/CsNoticeRepository.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/service/CustomerInquiryService.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/service/CustomerNoticeService.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/service/impl/CustomerInquiryServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/service/impl/CustomerNoticeServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/customerservice/entity/CsInquiry.java
  server/culinari/src/main/java/com/codestates/culinari/global/exception/ExceptionCode.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/ProfileDto.java
Labels: ✨ Feat, ⚒ Refactor

#49 [BE] 장바구니(Cart) 관련 테스트 코드 작성
  server/culinari/build.gradle
  server/culinari/src/main/java/com/codestates/culinari/order/service/impl/CartServiceImpl.java
  server/culinari/src/test/java/com/codestates/culinari/order/Stub/Stub.java
  server/culinari/src/test/java/com/codestates/culinari/order/controller/CartControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/order/service/impl/CartServiceImplTest.java
  server/culinari/src/test/java/config/TestSecurityConfig.java
Labels: ✨ Feat, ☔️ Test

#51 [BE] 주문(Orders, OrderDetail)관련 테스트 코드 작성
  server/culinari/src/main/java/com/codestates/culinari/order/service/impl/OrdersServiceImpl.java
  server/culinari/src/test/java/com/codestates/culinari/order/Stub/Stub.java
  server/culinari/src/test/java/com/codestates/culinari/order/controller/OrdersControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/order/service/impl/OrdersServiceImplTest.java
Labels: ✨ Feat, ☔️ Test

#54 [BE] 유저(Users, Profile)관련 테스트 코드 작성
  server/culinari/src/main/java/com/codestates/culinari/global/exception/ExceptionCode.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/UserDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/request/ProfilePatchRequest.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/request/SignUpDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/response/ProfileMyPageResponseDto.java
  server/culinari/src/test/java/com/codestates/culinari/user/controller/UserControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/user/service/impl/ProfileServiceImplTest.java
  server/culinari/src/test/java/com/codestates/culinari/user/service/impl/UserServiceImplTest.java
Labels: ⚒ Refactor, ☔️ Test

#56 [BE]Product 테스트코드 작성 및 Import Optimize
  server/culinari/src/main/java/com/codestates/culinari/config/SecurityConfig.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/dto/CustomUserDetails.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/handler/MemberAuthenticationFailureHandler.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/CsInquiryDto.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/entity/CsInquiry.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/CategoryController.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductCollectionsController.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductController.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/CategoryDetailDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/CategoryDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductInquiryDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewLikeDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/request/ProductReviewLikeRequest.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/request/ProductReviewRequest.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/CategoryDetailResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/CategoryResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductInquiryResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductResponseToPage.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductResponseWithCustomerService.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductReviewResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReviewLike.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductInquiryRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductCsService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/CategoryDetailServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/CategoryServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductCsServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/request/SignUpDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/response/ProfileMyPageReviewResponse.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/Users.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/ProfileService.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/impl/ProfileServiceImpl.java
  server/culinari/src/test/java/com/codestates/culinari/product/controller/CategoryControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/controller/ProductCollectionsControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/controller/ProductControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/service/impl/ProductCsServiceImplTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/service/impl/ProductServiceImplTest.java
Labels: ✨ Feat, ⚒ Refactor, ☔️ Test

#59 [FE] 자주 묻는 질문 컴포넌트 구현
  client/src/components/service/ManyQuestion.jsx
  client/src/components/service/ManyQuestionHeader.jsx
  client/src/components/service/ManyQuestionItem.jsx
Labels: ✨ Feat

#64 [BE] 고객센터 테스트코드 작성
  server/culinari/src/main/java/com/codestates/culinari/customercenter/controller/CustomerInquiryController.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/controller/CustomerNoticeController.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/request/CsInquiryRequest.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/request/CsNoticePost.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/response/CsInquiryResponse.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/response/CsNoticeResponse.java
  server/culinari/src/test/java/com/codestates/culinari/customercenter/controller/CustomerInquiryControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/customercenter/controller/CustomerNoticeControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/customercenter/service/CustomerInquiryServiceTest.java
  server/culinari/src/test/java/com/codestates/culinari/customercenter/service/CustomerNoticeServiceTest.java
Labels: ⚒ Refactor, ☔️ Test

#66 [FE] 마이페이지 기능구현
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/BasicButton.jsx
  client/src/components/ColorButton.jsx
  client/src/components/Header.jsx
  client/src/components/ListLayout.jsx
  client/src/components/MypageHead.jsx
  client/src/components/Tab.jsx
  client/src/components/TableBoard.jsx
  client/src/pages/mypage/buyItem.js
  client/src/pages/mypage/coupon.js
  client/src/pages/mypage/deliveryLook.js
  client/src/pages/mypage/deliverySet.js
  client/src/pages/mypage/index.js
  client/src/pages/mypage/inquiry.js
  client/src/pages/mypage/itemreview.js
  client/src/pages/mypage/itemreviewList.js
  client/src/pages/mypage/itemreviewWrite.js
  client/src/pages/mypage/orderitem.js
  client/src/pages/mypage/point.js
  client/src/pages/mypage/selectItem.js
  client/src/pages/mypage/userinfo.js
Labels: ✨ Feat

#63 [FE] 상품 상세 페이지 구성 컴포넌트, 레이아웃 구현
  client/package-lock.json
  client/package.json
  client/src/assets/star.svg
  client/src/components/QuantityBox.jsx
  client/src/pages/index.js
  client/src/pages/productDetail/index.js
  client/src/pages/productDetail/productAtf/ProductDataList.jsx
  client/src/pages/productDetail/productAtf/ProductHeader.jsx
  client/src/pages/productDetail/productAtf/ProductSelection.jsx
  client/src/pages/productDetail/productAtf/index.js
  client/src/pages/productDetail/productContent/Inquiry.jsx
  client/src/pages/productDetail/productContent/Nav.jsx
  client/src/pages/productDetail/productContent/Review.jsx
  client/src/pages/productDetail/productContent/index.js
Labels: ✨ Feat

#71 [BE] 고객센터 - 자주묻는 질문 구현
  server/culinari/src/main/java/com/codestates/culinari/customercenter/controller/CsFrequentlyAskedQuestionController.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/CsFrequentlyAskedQuestionDto.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/request/CsFrequentlyAskedQuestionRequest.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/response/CsFrequentlyAskedQuestionResponse.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/entity/CsFrequentlyAskedQuestion.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/repository/CsFrequentlyAskedQuestionRepository.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/repository/querydsl/CsFrequentlyAskedQuestionCustom.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/repository/querydsl/impl/CsFrequentlyAskedQuestionCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/service/CustomerFrequentlyAskedQuestionService.java
  server/culinari/src/main/java/com/codestates/culinari/customercenter/service/impl/CustomerFrequentlyAskedQuestionImpl.java
  server/culinari/src/test/java/com/codestates/culinari/customercenter/controller/CsFrequentlyAskedQuestionControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/customercenter/service/CustomerFrequentlyAskedQuestionServiceTest.java
Labels: ✨ Feat, ⚒ Refactor, ☔️ Test

#73 [BE] 통합검색/ 리뷰 별점/ 이미지 업로드 + #58
  server/culinari/src/main/java/com/codestates/culinari/global/file/FileStore.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/MypageController.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductController.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/SearchController.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewImageDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/request/ProductReviewRequest.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductResponseToPage.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductReviewResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReview.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReviewImage.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductReviewImageRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductCsService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductCsServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/ProfileService.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/impl/ProfileServiceImpl.java
  server/culinari/src/main/resources/application.yaml
  server/culinari/src/main/resources/data.sql
  server/culinari/src/test/java/com/codestates/culinari/product/controller/MypageControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/controller/ProductCollectionsControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/controller/ProductControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/service/impl/ProductCsServiceImplTest.java
  server/culinari/src/test/java/com/codestates/culinari/user/service/impl/ProfileServiceImplTest.java
Labels: ✨ Feat, ⚒ Refactor, ☔️ Test

#77 [FE] 상품 상세 페이지 후기, 문의 추가 기능 구현
  client/src/assets/answer-icon.svg
  client/src/assets/question-icon.svg
  client/src/components/AnswerIcon.jsx
  client/src/components/DeleteButton.jsx
  client/src/components/QuestionIcon.jsx
  client/src/pages/productDetail/index.js
  client/src/pages/productDetail/productContent/CreateInquiry.jsx
  client/src/pages/productDetail/productContent/Inquiry.jsx
  client/src/pages/productDetail/productContent/InquiryDetail.jsx
  client/src/pages/productDetail/productContent/ModalComponent.jsx
  client/src/pages/productDetail/productContent/Review.jsx
  client/src/pages/productDetail/productContent/ReviewModal.jsx
  client/src/pages/productDetail/productContent/index.js
Labels: ✨ Feat

#82 [BE] 찜목록 구현, 신상품 페이지 필터 추가
  server/culinari/src/main/java/com/codestates/culinari/global/search/SearchFilter.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/MypageController.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductCollectionsController.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductController.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductLikeDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductLike.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductLikeRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/querydsl/ProductRepositoryCustom.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/querydsl/ProductRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductServiceImpl.java
  server/culinari/src/main/resources/data.sql
Labels: ✨ Feat

#83 [BE] 결제 기능 구현
  server/culinari/src/main/java/com/codestates/culinari/global/exception/ExceptionCode.java
  server/culinari/src/main/java/com/codestates/culinari/order/controller/OrdersController.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/request/OrderRequest.java
  server/culinari/src/main/java/com/codestates/culinari/order/entitiy/OrderDetail.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/OrderDetailRepository.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/OrdersService.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/impl/OrdersServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/payment/constant/PayType.java
  server/culinari/src/main/java/com/codestates/culinari/payment/controller/PaymentController.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/PaymentDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/RefundDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/request/PaymentRequest.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/request/RefundRequest.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/PaymentCardResponse.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/PaymentFailResponse.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/PaymentInfoResponse.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/PaymentSuccessResponse.java
  server/culinari/src/main/java/com/codestates/culinari/payment/entity/Payment.java
  server/culinari/src/main/java/com/codestates/culinari/payment/entity/Refund.java
  server/culinari/src/main/java/com/codestates/culinari/payment/repository/PaymentRepository.java
  server/culinari/src/main/java/com/codestates/culinari/payment/repository/RefundRepository.java
  server/culinari/src/main/java/com/codestates/culinari/payment/service/PaymentService.java
  server/culinari/src/main/java/com/codestates/culinari/payment/service/impl/PaymentServiceImpl.java
  server/culinari/src/main/resources/application.yaml
  server/culinari/src/test/java/com/codestates/culinari/order/controller/OrdersControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/order/service/impl/OrdersServiceImplTest.java
Labels: ✨ Feat

#86 [BE] 주문, 결제 관련 코드 리팩토링
  server/culinari/src/main/java/com/codestates/culinari/order/dto/request/CartPatch.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/request/CartPost.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/CartRepository.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/OrdersRepository.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrdersRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/impl/CartServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/request/PaymentRequest.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/request/RefundRequest.java
  server/culinari/src/test/java/com/codestates/culinari/order/Stub/Stub.java
  server/culinari/src/test/java/com/codestates/culinari/order/controller/OrdersControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/order/service/impl/CartServiceImplTest.java
Labels: ⚒ Refactor

#89 [BE] 추가 및 리팩토링 된 로직에 따른 테스트 코드 리팩토링
  server/culinari/src/test/java/com/codestates/culinari/product/controller/MypageControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/controller/ProductCollectionsControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/service/impl/ProductServiceImplTest.java
Labels: ☔️ Test

#91 [BE] Dto 리팩토링 및 코드 점검
  server/culinari/src/main/java/com/codestates/culinari/customercenter/entity/CsFrequentlyAskedQuestion.java
  server/culinari/src/main/java/com/codestates/culinari/global/file/FileStore.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductController.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/SearchController.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/request/ProductReviewRequest.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductWithCustomerServiceResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReviewImage.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/querydsl/ProductRepositoryCustom.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/querydsl/ProductRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductCsService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductCsServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductServiceImpl.java
  server/culinari/src/test/java/com/codestates/culinari/customercenter/controller/CustomerInquiryControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/customercenter/service/CustomerFrequentlyAskedQuestionServiceTest.java
  server/culinari/src/test/java/com/codestates/culinari/customercenter/service/CustomerInquiryServiceTest.java
  server/culinari/src/test/java/com/codestates/culinari/customercenter/service/CustomerNoticeServiceTest.java
  server/culinari/src/test/java/com/codestates/culinari/order/controller/OrdersControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/order/service/impl/OrdersServiceImplTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/controller/CategoryControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/controller/MypageControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/controller/ProductCollectionsControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/controller/ProductControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/service/impl/ProductCsServiceImplTest.java
  server/culinari/src/test/java/com/codestates/culinari/product/service/impl/ProductServiceImplTest.java
  server/culinari/src/test/java/com/codestates/culinari/user/controller/UserControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/user/service/impl/UserServiceImplTest.java
  server/culinari/src/test/resources/testImage/testImage.jpeg
Labels: ⚒ Refactor, ☔️ Test

#93 [FE] 신상품, 베스트 페이지 구성 컴포넌트, 레이아웃 구현
  client/src/App.js
  client/src/components/CheckBox.jsx
  client/src/components/Header.jsx
  client/src/components/ProductItem.jsx
  client/src/constants/BASE_URL.js
  client/src/pages/collection/index.js
  client/src/pages/productDetail/productContent/CreateInquiry.jsx
Labels: ✨ Feat

#92 [BE] 결제 기능 구현
  server/culinari/src/main/java/com/codestates/culinari/global/exception/ExceptionCode.java
  server/culinari/src/main/java/com/codestates/culinari/payment/controller/PaymentController.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/PaymentDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/entity/Payment.java
  server/culinari/src/main/java/com/codestates/culinari/payment/repository/PaymentRepository.java
  server/culinari/src/main/java/com/codestates/culinari/payment/repository/querydsl/PaymentRepositoryCustom.java
  server/culinari/src/main/java/com/codestates/culinari/payment/repository/querydsl/PaymentRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/payment/service/PaymentService.java
  server/culinari/src/main/java/com/codestates/culinari/payment/service/impl/PaymentServiceImpl.java
Labels: ✨ Feat

#94 [BE] 결제 기능 테스트 작성
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/PaymentCardResponse.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/PaymentSuccessResponse.java
  server/culinari/src/test/java/com/codestates/culinari/order/Stub/Stub.java
  server/culinari/src/test/java/com/codestates/culinari/order/controller/OrdersControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/order/service/impl/OrdersServiceImplTest.java
  server/culinari/src/test/java/com/codestates/culinari/payment/controller/PaymentControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/payment/service/impl/PaymentServiceImplTest.java
Labels: ✨ Feat

#97 [FE] 검색결과 페이지 구성 레이아웃 구현
  client/src/App.js
  client/src/components/Header.jsx
  client/src/pages/search/index.js
Labels: ✨ Feat

#99 [BE] 결제, 주문 관련 DTO 변경 및 리팩토링
  server/culinari/src/main/java/com/codestates/culinari/order/controller/CartController.java
  server/culinari/src/main/java/com/codestates/culinari/order/controller/OrdersController.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/CartDto.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/OrderDetailDto.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/OrderDto.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/response/CartResponse.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/response/OrderDetailResponse.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/response/OrderResponse.java
  server/culinari/src/main/java/com/codestates/culinari/order/entitiy/Cart.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/CartService.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/OrdersService.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/impl/CartServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/impl/OrdersServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/pagination/PageResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/controller/PaymentController.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/PaymentDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/RefundDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/PaymentCardResponse.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/PaymentInfoResponse.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/PaymentResponseToPage.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/PaymentSuccessResponse.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/toss/PaymentTossDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/toss/detail/PaymentTossCancelDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/toss/detail/PaymentTossCardDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/toss/detail/PaymentTossCashReceiptDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/toss/detail/PaymentTossCheckoutDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/toss/detail/PaymentTossDiscountDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/toss/detail/PaymentTossEasyPayDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/toss/detail/PaymentTossFailureDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/toss/detail/PaymentTossGiftCertificateDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/toss/detail/PaymentTossMobilePhoneDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/toss/detail/PaymentTossReceiptDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/toss/detail/PaymentTossTransferDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/toss/detail/PaymentTossVirtualAccountDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/entity/Payment.java
  server/culinari/src/main/java/com/codestates/culinari/payment/repository/PaymentRepository.java
  server/culinari/src/main/java/com/codestates/culinari/payment/service/PaymentService.java
  server/culinari/src/main/java/com/codestates/culinari/payment/service/impl/PaymentServiceImpl.java
  server/culinari/src/test/java/com/codestates/culinari/order/Stub/Stub.java
  server/culinari/src/test/java/com/codestates/culinari/order/controller/CartControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/order/controller/OrdersControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/payment/controller/PaymentControllerTest.java
  server/culinari/src/test/java/com/codestates/culinari/payment/service/impl/PaymentServiceImplTest.java
Labels: ✨ Feat, ⚒ Refactor

#105 [FE] 상품 상세 페이지 서버 연결, 장바구니 담기 기능 구현
  client/src/App.js
  client/src/pages/productDetail/index.js
  client/src/pages/productDetail/productAtf/ProductDataList.jsx
  client/src/pages/productDetail/productAtf/ProductHeader.jsx
  client/src/pages/productDetail/productAtf/ProductSelection.jsx
  client/src/pages/productDetail/productAtf/index.js
  client/src/pages/productDetail/productContent/Inquiry.jsx
  client/src/pages/productDetail/productContent/index.js
Labels: ✨ Feat

#101 [BE] 이미지 전송 리팩토링
  server/culinari/.gitignore
  server/culinari/build.gradle
  server/culinari/src/main/java/com/codestates/culinari/global/file/FileStore.java
  server/culinari/src/main/java/com/codestates/culinari/global/file/S3Config.java
  server/culinari/src/main/java/com/codestates/culinari/global/file/S3Uploader.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductImageDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewImageDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/request/ProductReviewRequest.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductResponseToPage.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductReviewResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductWithCustomerServiceResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/Product.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductImage.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReview.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReviewImage.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductCsService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductCsServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductServiceImpl.java
  server/culinari/src/main/resources/data.sql
Labels: ✨ Feat, ⚒ Refactor

#107 [FE]마이페이지 배송지설정 기능구현
  client/.env
  client/src/App.js
  client/src/components/BasicButton.jsx
  client/src/components/BasicInput.jsx
  client/src/components/CheckBox.jsx
  client/src/components/Guidance.jsx
  client/src/components/ListLayout.jsx
  client/src/components/Modalbutton.jsx
  client/src/components/MypageHead.jsx
  client/src/components/PatchModal.jsx
  client/src/components/Postmodal.jsx
  client/src/components/SideInput.jsx
  client/src/components/Tab.jsx
  client/src/pages/mypage/buyItem.js
  client/src/pages/mypage/coupon.js
  client/src/pages/mypage/deliveryLook.js
  client/src/pages/mypage/deliverySet.js
  client/src/pages/mypage/index.js
  client/src/pages/mypage/userinfo.js
Labels: ✨ Feat

#115 #114 - fix: 메인페이지 배너 높이 설정
  client/src/components/MainBanner.jsx
Labels: ✨ Feat

#117 [FE] 상품 리스트 렌더 오류 수정
  client/src/components/ProductItem.jsx
  client/src/pages/collection/index.js
Labels: 💊!HOTFIX

#110 [BE] 작성한 후기, 작성 가능한 후기 나누기
  server/culinari/src/main/java/com/codestates/culinari/destination/entity/Destination.java
  server/culinari/src/main/java/com/codestates/culinari/global/search/SearchFilter.java
  server/culinari/src/main/java/com/codestates/culinari/order/entitiy/OrderDetail.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/OrderDetailRepository.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/OrdersService.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/impl/OrdersServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/MypageController.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductReviewDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/request/ProductReviewRequest.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductReviewResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/Product.java
  server/culinari/src/main/java/com/codestates/culinari/product/entitiy/ProductReview.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductReviewRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductCsService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductCsServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/response/ProfileMyPageReviewEnableResponse.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/response/ProfileMyPageReviewExistResponse.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/response/ProfileMyPageReviewResponse.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/impl/UserServiceImpl.java
  server/culinari/src/main/resources/data.sql
  server/culinari/src/test/java/com/codestates/culinari/product/service/impl/ProductCsServiceImplTest.java
Labels: ✨ Feat

#121 [BE] 배송지 문제점 해결 및 프로필 주소 삭제
  server/culinari/src/main/java/com/codestates/culinari/user/controller/UserController.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/ProfileDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/request/ProfilePatchRequest.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/request/SignUpDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/request/UserPatchPasswordRequest.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/response/ProfileMyPageResponseDto.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/Profile.java
  server/culinari/src/main/java/com/codestates/culinari/user/entitiy/Users.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/UserService.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/impl/ProfileServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/impl/UserServiceImpl.java
Labels: ⚒ Refactor

#123 [BE] 마이페이지 - 자주 주문한 상품 기능 구현
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrdersRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductCollectionsController.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductResponseToPage.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/querydsl/ProductRepositoryCustom.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/querydsl/ProductRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductServiceImpl.java
Labels: ✨ Feat

#126 [FE] 고객센터 페이지 디자인 수정
  client/src/components/service/OftenDetail.jsx
  client/src/components/service/OneOnOne.jsx
  client/src/components/service/OneOnOneDetail.jsx
  client/src/components/service/OneOnOneItem.jsx
  client/src/components/service/ServiceDetailpage.jsx
  client/src/styles/OneOnOneStyle.js
Labels: 💄 CSS

#124 [FE] 마이페이지 컴포넌트별 기능 및 디자인 변경
  client/package-lock.json
  client/package.json
  client/src/components/ListLayout.jsx
  client/src/components/PatchModal.jsx
  client/src/components/Postmodal.jsx
  client/src/components/TableBoard.jsx
  client/src/components/signup/SignupForm.jsx
  client/src/pages/mypage/buyItem.js
  client/src/pages/mypage/coupon.js
  client/src/pages/mypage/deliveryLook.js
  client/src/pages/mypage/deliverySet.js
  client/src/pages/mypage/index.js
  client/src/pages/mypage/itemreviewList.js
  client/src/pages/mypage/orderitem.js
  client/src/pages/mypage/point.js
  client/src/pages/mypage/selectItem.js
  client/src/pages/mypage/userinfo.js
Labels: ✨ Feat

#129 [FE] ProductItem props 수정
  client/src/components/ProductItem.jsx
  client/src/components/ProductItemSlider.jsx
  client/src/pages/collection/index.js
  client/src/pages/mypage/buyItem.js
  client/src/pages/mypage/selectItem.js
  client/src/pages/search/index.js
Labels: 💊!HOTFIX

#130 [FE] 카테고리 리스트 렌더링 구현
  client/src/App.js
  client/src/components/header/LogoutHeader.jsx
Labels: ✨ Feat

#134 [FE] 회원가입 페이지 유효성검사 수정
  client/src/components/signup/GuideModal.jsx
  client/src/components/signup/ModalCotainer.jsx
  client/src/components/signup/SignupForm.jsx
  client/src/styles/signupStyle.js
Labels: ✨ Feat

#136 [FE] 검색 결과 페이지 기능 구현
  client/src/components/header/LogoutHeader.jsx
  client/src/pages/search/index.js
Labels: ✨ Feat

#139 [BE] 주문, 결제 FE와 API 요구사항 조정
  server/culinari/src/main/java/com/codestates/culinari/order/constant/StatusType.java
  server/culinari/src/main/java/com/codestates/culinari/order/controller/CartController.java
  server/culinari/src/main/java/com/codestates/culinari/order/controller/OrdersController.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/OrderDetailDto.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/request/CartDelete.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/request/CartPost.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/response/CartResponse.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/response/OrderDetailResponse.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/CartRepository.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/OrderDetailRepository.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/CartRepositoryCustom.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/CartRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrderDetailRepositoryCustom.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrderDetailRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrdersRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/CartService.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/OrdersService.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/impl/CartServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/impl/OrdersServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/payment/controller/PaymentController.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/RefundDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/request/PaymentRequest.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/request/RefundRequest.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/PaymentInfoResponse.java
  server/culinari/src/main/java/com/codestates/culinari/payment/service/PaymentService.java
  server/culinari/src/main/java/com/codestates/culinari/payment/service/impl/PaymentServiceImpl.java
Labels: ✨ Feat, ⚒ Refactor

#153 [FE] 메인페이지 상품 이미지 오류 수정
  client/src/components/ProductItemSlider.jsx
Labels: 🥺 Fix

#156 [FE] 장바구니 담기 요청 코드 수정
  client/src/pages/productDetail/productAtf/ProductSelection.jsx
Labels: 🥺 Fix

#164 [FE] 카테고리 페이지 레이아웃 및 기능 구현 #157
  client/src/components/header/LogoutHeader.jsx
  client/src/pages/search/index.js
Labels: ✨ Feat

#167 [FE] 장바구니 삭제 api 수정
  client/src/components/cart/CartProductItem.jsx
  client/src/pages/cart/index.js
Labels: 🥺 Fix

#169 [FE] 장바구니 페이지 css, 배송비 부분 수정
  client/src/pages/cart/index.js
Labels: 🥺 Fix

#174 [FE] 결제페이지에서 장바구니 id 데이터 전달
  client/package-lock.json
  client/package.json
  client/src/app/reducer/productId2Pay.js
  client/src/app/store.js
  client/src/components/cart/CartProductItem.jsx
  client/src/components/pay/index.js
  client/src/index.js
  client/src/pages/cart/index.js
Labels: ✨ Feat

#178 [BE] best 상품 구현, 및 머지 충돌 해결
  server/culinari/src/main/java/com/codestates/culinari/config/security/filter/JwtVerificationFilter.java
  server/culinari/src/main/java/com/codestates/culinari/config/security/jwt/JwtTokenizer.java
  server/culinari/src/main/java/com/codestates/culinari/order/dto/request/CartDelete.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/CartRepository.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/CartRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductCollectionsController.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/querydsl/ProductRepositoryCustom.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/querydsl/ProductRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductServiceImpl.java
Labels: ✨ Feat, 🥺 Fix, ⚒ Refactor

#181 [FE] 장바구니 스토어 총 주문 금액 데이터 추가
  client/src/app/reducer/productId2Pay.js
  client/src/app/store.js
  client/src/components/pay/index.js
  client/src/pages/cart/index.js
Labels: ✨ Feat

#184 [FE] 결제페이지 새로고침 시 상태 데이터 초기화되는 현상 수정
  client/package-lock.json
  client/package.json
  client/src/app/store.js
  client/src/index.js
Labels: 🥺 Fix

#185 [FE] 결제 페이지 Toss 결제 기능 구현
  client/package-lock.json
  client/package.json
  client/src/components/pay/InfoCheck.jsx
  client/src/components/pay/OrderInfo.jsx
  client/src/components/pay/PayInfo.jsx
  client/src/components/pay/ShipInfo.jsx
  client/src/components/pay/index.js
Labels: ✨ Feat

#188 [FE] 신상품, 베스트 페이지 정렬 기능, 카테고리 검색 기능
  client/src/App.js
  client/src/components/header/LogoutHeader.jsx
  client/src/pages/collection/CategoryList.jsx
  client/src/pages/collection/index.js
Labels: ✨ Feat

#192 [FE] 결제완료 후 결제정보 서버에 전송
  client/src/components/pay/SuccessPayment.jsx
Labels: ✨ Feat

#193 [FE] 검색 기능 오류 수정
  client/src/pages/search/index.js
Labels: 💊!HOTFIX

#196 [FE] ProductItemSlider 상품 리스트 수정
  client/src/components/ProductItemSlider.jsx
  client/src/pages/index.js
Labels: ✨ Feat

#197 [FE] 페이지네이션 컴포넌트 구현, 페이지네이션 컴포넌트 적용
  client/src/components/Pagination.jsx
  client/src/pages/collection/index.js
  client/src/pages/productDetail/productContent/Inquiry.jsx
  client/src/pages/productDetail/productContent/Review.jsx
  client/src/pages/productDetail/productContent/index.js
  client/src/pages/search/index.js
Labels: ✨ Feat

#198 [FE] 헤더 컴포넌트 추가 수정
  client/src/components/header/Header.jsx
Labels: ✨ Feat

#182 [BE] 시큐리티 권한 강화
  server/culinari/src/main/java/com/codestates/culinari/config/SecurityConfig.java
Labels: ✨ Feat, ⚒ Refactor

#200 [FE] 고객센터 페이지 기본 페이지 설정 css 수정
  client/src/components/service/OftenDetail.jsx
  client/src/components/service/OneOnOne.jsx
  client/src/components/service/OneOnOneInquiry.jsx
  client/src/components/service/ServiceDetailpage.jsx
  client/src/components/service/data.json
  client/src/components/service/index.js
Labels: ✨ Feat

#201 [BE] 자잘한 코드 변경
  server/culinari/src/main/java/com/codestates/culinari/global/file/S3Uploader.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/OrderDetailRepository.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/CartRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductController.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/ProductLikeDto.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductInquiryResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductReviewResponse.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductInquiryRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductReviewRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductCsService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/ProductService.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductCsServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/response/ProfileMyPageReviewExistResponse.java
  server/culinari/src/test/java/com/codestates/culinari/product/controller/ProductControllerTest.java
Labels: 🥺 Fix, ⚒ Refactor

#207 [FE] Footer 컴포넌트 레이아웃 작성
  client/public/img/github-logo.png
  client/src/App.js
  client/src/assets/logo.jpg
  client/src/components/footer/Footer.jsx
Labels: 💄 CSS, ✨ Feat

#209 [FE] 장바구니 페이지 오류 수정
  client/src/pages/cart/index.js
Labels: 🥺 Fix

#211 [FE] 헤더 컴포넌트 디자인 수정
  client/src/assets/fitlogo.png
  client/src/components/header/Header.jsx
Labels: 💄 CSS

#214 [FE] Footer 컴포넌트 github 로고 경로 수정
  client/src/assets/github-logo.png
  client/src/components/footer/Footer.jsx
Labels: 💄 CSS

#215 [FE] 전체적인 오류, css 수정 #213
  client/src/components/Pagination.jsx
  client/src/components/header/Header.jsx
  client/src/pages/cart/index.js
  client/src/pages/collection/index.js
  client/src/pages/productDetail/productAtf/ProductHeader.jsx
  client/src/pages/productDetail/productAtf/ProductSelection.jsx
  client/src/pages/productDetail/productContent/CreateInquiry.jsx
  client/src/pages/productDetail/productContent/EditInquiry.jsx
  client/src/pages/productDetail/productContent/Inquiry.jsx
  client/src/pages/productDetail/productContent/Review.jsx
  client/src/pages/productDetail/productContent/index.js
  client/src/pages/search/index.js
Labels: 💄 CSS, 🥺 Fix

#217 [FE] 리스트 상품이 0개인 경우 이미지 삽입
  client/src/assets/product_none.png
  client/src/pages/collection/index.js
  client/src/pages/search/index.js
Labels: 💄 CSS

#219 [FE] 카테고리 GET 요청 오류 수정
  client/src/pages/search/index.js
Labels: 🥺 Fix

#221 [FE] 문의하기 컴포넌트 props 수정, 비로그인 시 로그인 페이지로 유도 구현
  client/src/pages/productDetail/productContent/CreateInquiry.jsx
  client/src/pages/productDetail/productContent/Inquiry.jsx
Labels: 🚀 Chore

#150 [FE] 마이페이지 유저정보 기능구현
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/components/AfterReviewList.jsx
  client/src/components/BasicButton.jsx
  client/src/components/BasicInput.jsx
  client/src/components/BeforeReviewList.jsx
  client/src/components/CountBox.jsx
  client/src/components/FilterBar.jsx
  client/src/components/Guidance.jsx
  client/src/components/ListLayout.jsx
  client/src/components/MypageHead.jsx
  client/src/components/PaginationBtn.jsx
  client/src/components/PatchModal.jsx
  client/src/components/Postmodal.jsx
  client/src/components/ReviewStar.jsx
  client/src/components/Tab.jsx
  client/src/components/signup/GenderRadio.jsx
  client/src/components/signup/ModalCotainer.jsx
  client/src/pages/mypage/buyItem.js
  client/src/pages/mypage/deliveryLook.js
  client/src/pages/mypage/deliverySet.js
  client/src/pages/mypage/index.js
  client/src/pages/mypage/itemreviewList.js
  client/src/pages/mypage/itemreviewWrite.js
  client/src/pages/mypage/orderitem.js
  client/src/pages/mypage/selectItem.js
  client/src/pages/mypage/userinfo.js
Labels: ✨ Feat, 🥺 Fix

#225 [FE] 메인배너 이미지 수정
  client/src/assets/banner-image1.png
  client/src/assets/banner-image2.png
  client/src/assets/banner-image3.png
  client/src/components/MainBanner.jsx
Labels: 💄 CSS
