Repository codestates-seb/seb41_main_017, pull requests merged in 2023-02, with the labels that each got.

#228 #226 - feat: 회원가입 페이지 필수입력사항 미작성시 가입실패 모달 렌더
  client/src/components/signup/SignupForm.jsx
Labels: ✨ Feat

#229 [FE] 후기글 문의글 없을 경우 이미지 추가
  client/src/assets/docs-icon.png
  client/src/pages/productDetail/productContent/Inquiry.jsx
  client/src/pages/productDetail/productContent/Review.jsx
Labels: ✨ Feat

#231 [FE] 회원가입 페이지 GenderRadio setState 에러 해결
  client/src/components/signup/GenderRadio.jsx
  client/src/components/signup/SignupForm.jsx
Labels: ✨ Feat, 🥺 Fix

#233 [FE] ProductItem 컴포넌트 가격부분 css 수정
  client/src/components/ProductItem.jsx
Labels: 💄 CSS

#235 [FE] 마이페이지 기능구현
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/AuthRoute.js
  client/src/components/OtherPagination.jsx
  client/src/components/PatchModal.jsx
  client/src/components/Postmodal.jsx
  client/src/components/header/Header.jsx
  client/src/components/signup/GenderRadio.jsx
  client/src/pages/cart/index.js
  client/src/pages/mypage/deliveryLook.js
  client/src/pages/mypage/deliverySet.js
  client/src/pages/mypage/index.js
  client/src/pages/mypage/inquiry.js
  client/src/pages/mypage/orderitem.js
  client/src/pages/mypage/userinfo.js
Labels: ✨ Feat

#236 #223 - feat: 1:1문의 컴포넌트 페이지네이션 구현
  client/src/components/OtherPagination.jsx
  client/src/components/service/OneOnOne.jsx
Labels: ✨ Feat

#244 [FE] 후기 요청 쿼리 수정, 후기 상품명 렌더링
  client/src/pages/productDetail/productContent/Review.jsx
  client/src/pages/productDetail/productContent/index.js
Labels: ✨ Feat, 🥺 Fix

#245 [FE] 정렬 버튼 클릭 이벤트 범위 수정
  client/src/pages/collection/index.js
  client/src/pages/productDetail/productContent/Review.jsx
  client/src/pages/search/index.js
Labels: 🥺 Fix

#248 [FE] 상품 상세페이지 상품 상세 내용 수정
  client/src/pages/productDetail/productContent/index.js
Labels: 💄 CSS

#249 [BE] 마이 페이지 카운트 데이터 API 구현 및 잡다한 변경
  server/culinari/src/main/java/com/codestates/culinari/order/entitiy/Orders.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrderDetailRepositoryCustom.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrderDetailRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrdersRepositoryCustom.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrdersRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/impl/CartServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/order/service/impl/OrdersServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/RefundDto.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/request/RefundRequest.java
  server/culinari/src/main/java/com/codestates/culinari/payment/dto/response/PaymentInfoResponse.java
  server/culinari/src/main/java/com/codestates/culinari/payment/service/impl/PaymentServiceImpl.java
  server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductController.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/ProductLikeRepository.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/querydsl/ProductRepositoryCustom.java
  server/culinari/src/main/java/com/codestates/culinari/product/repository/querydsl/ProductRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/user/controller/MyPageController.java
  server/culinari/src/main/java/com/codestates/culinari/user/dto/response/MyPageCountResponse.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/MyPageService.java
  server/culinari/src/main/java/com/codestates/culinari/user/service/impl/MyPageServiceImpl.java
Labels: ✨ Feat, ⚒ Refactor

#252 [FE] 찜 등록, 취소 시 토스트 메시지 렌더링 구현
  client/src/components/cart/CartProductItem.jsx
Labels: ✨ Feat

#255 [FE] 불필요한 footer 태그 삭제
  client/src/App.js
Labels: 🥺 Fix

#258 [FE] favicon, react title 변경
  client/public/favicon.ico
  client/public/index.html
Labels: ✨ Feat

#260 [FE] 찜 등록, 취소 시 alert 표시
  client/src/pages/productDetail/productAtf/ProductHeader.jsx
Labels: ✨ Feat

#261 #259 - feat: 회원가입 페이지 주소 input 수정
  client/src/components/signup/SignupForm.jsx
  client/src/styles/signupStyle.js
Labels: ✨ Feat

#264 [FE] 상품 후기 이미지 렌더링, 상품 후기 상세 모달 수정
  client/src/pages/productDetail/productContent/Review.jsx
  client/src/pages/productDetail/productContent/ReviewModal.jsx
Labels: ✨ Feat

#266 [FE] 상품 문의 작성일 수정
  client/src/pages/productDetail/productContent/InquiryDetail.jsx
Labels: 🥺 Fix

#267 #263 - feat: 회원가입 페이지 유효성 검사 수정
  client/src/components/signup/SignupForm.jsx
Labels: ✨ Feat

#269 [FE] API 요청 url 모두 env로 변경
  client/.env
  client/.gitignore
  client/src/components/answer/AnswerItem.jsx
  client/src/components/answer/index.js
  client/src/components/cart/CartProductItem.jsx
  client/src/components/header/Header.jsx
  client/src/components/login/LoginInputForm.jsx
  client/src/components/pay/SuccessPayment.jsx
  client/src/components/pay/index.js
  client/src/components/service/OneOnOne.jsx
  client/src/components/service/OneOnOneDetail.jsx
  client/src/components/signup/ModalCotainer.jsx
  client/src/components/signup/SignupForm.jsx
  client/src/constants/BASE_URL.js
  client/src/pages/cart/index.js
  client/src/pages/collection/index.js
  client/src/pages/index.js
  client/src/pages/productDetail/index.js
  client/src/pages/productDetail/productAtf/ProductHeader.jsx
  client/src/pages/productDetail/productAtf/ProductSelection.jsx
  client/src/pages/productDetail/productContent/CreateInquiry.jsx
  client/src/pages/productDetail/productContent/EditInquiry.jsx
  client/src/pages/productDetail/productContent/Inquiry.jsx
  client/src/pages/productDetail/productContent/InquiryDetail.jsx
  client/src/pages/productDetail/productContent/Review.jsx
  client/src/pages/search/index.js
Labels: 🚀 Chore

#270 [BE] 환불한 주문, 주문 상세 조회하지 않기
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrderDetailRepositoryCustom.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrderDetailRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrdersRepositoryCustomImpl.java
  server/culinari/src/main/java/com/codestates/culinari/payment/service/impl/PaymentServiceImpl.java
Labels: ✨ Feat

#272 [FE] 상품 상세 페이지 nav css 미적용 부분 수정
  client/src/pages/productDetail/productContent/index.js
Labels: 🥺 Fix

#273 [FE] 마이페이지 기능구현
  client/src/App.js
  client/src/AuthRoute.js
  client/src/components/AfterReviewList.jsx
  client/src/components/CountBox.jsx
  client/src/components/MypageItemQuantity.jsx
  client/src/components/OtherPagination.jsx
  client/src/components/header/Header.jsx
  client/src/components/service/OneOnOne.jsx
  client/src/pages/cart/index.js
  client/src/pages/mypage/buyItem.js
  client/src/pages/mypage/deliveryLook.js
  client/src/pages/mypage/index.js
  client/src/pages/mypage/inquiry.js
  client/src/pages/mypage/itemreviewList.js
  client/src/pages/mypage/itemreviewWrite.js
  client/src/pages/mypage/orderitem.js
  client/src/pages/mypage/selectItem.js
Labels: ✨ Feat

#274 [FE] 마이페지이 내문의 기능구현
  client/src/App.css
  client/src/components/MypageItem.jsx
  client/src/pages/mypage/inquiry.js
Labels: ✨ Feat

#280 [FE] 장바구니 no_cart 이미지 에러 수정
  client/src/assets/no_carts.png
  client/src/pages/cart/index.js
Labels: 🥺 Fix
